export const GET_DATA_SERVICE_REQUESTED = 'GET_DATA_SERVICE_REQUESTED' as const;
export const GET_DATA_SERVICE_SUCCEEDED = 'GET_DATA_SERVICE_SUCCEEDED' as const;
export const GET_DATA_SERVICE_FAILED = 'GET_DATA_SERVICE_FAILED' as const;

export const PATCH_DATA_SERVICE_REQUESTED = 'PATCH_DATA_SERVICE_REQUESTED' as const;
export const PATCH_DATA_SERVICE_SUCCEEDED = 'PATCH_DATA_SERVICE_SUCCEEDED' as const;
export const PATCH_DATA_SERVICE_FAILED = 'PATCH_DATA_SERVICE_FAILED' as const;

export const DELETE_DATA_SERVICE_REQUESTED = 'DELETE_DATA_SERVICE_REQUESTED' as const;
export const DELETE_DATA_SERVICE_SUCCEEDED = 'DELETE_DATA_SERVICE_SUCCEEDED' as const;
export const DELETE_DATA_SERVICE_FAILED = 'DELETE_DATA_SERVICE_FAILED' as const;

export const IMPORT_DATA_SERVICE_REQUESTED = 'IMPORT_DATA_SERVICE_REQUESTED' as const;
export const IMPORT_DATA_SERVICE_SUCCEEDED = 'IMPORT_DATA_SERVICE_SUCCEEDED' as const;
export const IMPORT_DATA_SERVICE_FAILED = 'IMPORT_DATA_SERVICE_FAILED' as const;

export const RESET_DATA_SERVICE = 'RESET_DATA_SERVICE' as const;
