export const FETCH_ALL_DATASERVICES_REQUESTED = 'FETCH_ALL_DATASERVICES_REQUESTED' as const;
export const FETCH_ALL_DATASERVICES_SUCCEEDED = 'FETCH_ALL_DATASERVICES_SUCCEEDED' as const;
export const FETCH_ALL_DATASERVICES_FAILED = 'FETCH_ALL_DATASERVICES_FAILED' as const;

export const SORT_DATASERVICES = 'SORT_DATASERVICES' as const;
