export const FETCH_ALL_DATA_SERVICES_REQUESTED = 'FETCH_ALL_DATA_SERVICES_REQUESTED' as const;
export const FETCH_ALL_DATA_SERVICES_SUCCEEDED = 'FETCH_ALL_DATA_SERVICES_SUCCEEDED' as const;
export const FETCH_ALL_DATA_SERVICES_FAILED = 'FETCH_ALL_DATA_SERVICES_FAILED' as const;

export const SORT_DATA_SERVICES = 'SORT_DATA_SERVICES' as const;
